# Generated by Django 5.2.7 on 2025-10-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('show_on_profile', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='ai/videos/')),
            ],
            options={
                'ordering': ['-priority'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('show_on_profile', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='photography/')),
            ],
            options={
                'ordering': ['-priority'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Videography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('show_on_profile', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('video', models.FileField(upload_to='videography/')),
            ],
            options={
                'ordering': ['-priority'],
                'abstract': False,
            },
        ),
    ]
