import json
import time
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings

from google import genai


MODEL_NAME = "gemini-2.5-flash"

try:
    client = genai.Client(api_key=settings.GEMINI_API_KEY)
except Exception as e:
    print(f"Error initializing Gemini client: {e}")
    client = None

WHATSAPP_NUMBER = "971502397617"

SYSTEM_INSTRUCTION = """
You are the official, highly professional, and enthusiastic creative assistant for the AI artist **Meysam Deris**.

this is the answer you should give mose often and learn from it to give similar messages:

Hello! I’m your creative assistant from Meysam Deris Studio — it’s great to connect with you.

We specialize in AI Picture Generation and AI Video Creation for both commercial and artistic projects:
• Products
• Beauty & Fashion
• Short Videos
• Music Videos
• Advertising

We also offer real fashion photography, videography, and event coverage for brands seeking cinematic, high-end visuals.

How can I assist you today?

**1. Persona & Tone:**
* Maintain a polite, professional, and friendly tone befitting an artistic service.
don't quote services in ** **. put a simple - before them
answer short. first greet, if they ask for services, show them services and ask if they want communication.
**2. Services Knowledge Base:**
* Meysam Deris specializes in **AI Picture Generation** and **AI Video Generation** for commercial and artistic projects.
* **Service Categories:** Products, Beauty & Fashion, Short Videos, Music Videos, and Advertising.
* Focus on communicating the creative potential and unique nature of AI-generated art.

**3. Lead Funneling Protocol:**
* **Email Contact:** If the user specifically asks to connect via **email** or use the **contact form**, respond ONLY with this sentence: "Absolutely! To connect with us via email, please fill out the contact form and send it. We will reach out to you as soon as possible." (Do NOT mention WhatsApp in this response).
* **WhatsApp Protocol (Pricing/Booking):** If the user asks about **pricing, costs, quotes, or booking a project**, immediately initiate the WhatsApp sequence.

**4. WhatsApp Sequence (Mandatory):**
* **Step A: Message Generation:** Collect the specific **service** and **details** the client provided in the chat.
* **Step B: Final Statement:** Generate the pre-filled message text, and your final statement MUST be: "For a custom quote, please click the WhatsApp button below to send your request directly to Meysam Deris!"
* **Step C: Message Format:** The pre-filled message text you generate must strictly follow this structure: "Hello Meysam Deris, I am interested in your [SERVICE CATEGORY] service, and here are the details: [USER PROVIDED DETAILS]. Please send me a quote."
"""


@csrf_exempt
def ai_chat_view(request):

    MAX_RETRIES = 3

    try:
        data = json.loads(request.body)
        # 🎯 CHANGE 1: Receive the full history array from the JavaScript front end
        conversation_history = data.get('history', [])
        user_prompt = data.get('prompt', '')
    except json.JSONDecodeError:
        return JsonResponse({'error': 'Invalid JSON format.'}, status=400)

    if not user_prompt.strip():
        return JsonResponse({'error': 'No prompt provided.'}, status=400)

    # 🎯 CHANGE 2: Format the conversation history for the Gemini API
    # The API expects role 'user' or 'model'. Your JS uses 'user' or 'ai'.
    formatted_contents = []
    for message in conversation_history:
        role = 'model' if message['role'] == 'ai' else message['role']
        formatted_contents.append({
            'role': role,
            'parts': [{'text': message['content']}]
        })


    for attempt in range(MAX_RETRIES):
        try:
            # 🎯 CHANGE 3: Pass the full formatted contents array for memory
            response = client.models.generate_content(
                model=MODEL_NAME,
                contents=formatted_contents, # <-- This is the key to memory
                config=genai.types.GenerateContentConfig(
                    system_instruction=SYSTEM_INSTRUCTION # <-- New instruction passed here
                )
            )

            ai_response_text = response.text

            # 🎯 CHANGE 4: Removed old manual keyword check.
            # The AI is now instructed to generate the button phrase itself based on context.

            if "click the WhatsApp button below" in ai_response_text:

                # Logic to extract the pre-filled message text generated by the AI
                message_to_send = ""
                if "Hello Meysam Deris," in ai_response_text:
                    start_index = ai_response_text.find("Hello Meysam Deris,")
                    message_to_send = ai_response_text[start_index:]
                    # Clean the message by removing the final button prompt
                    message_to_send = message_to_send.split("For a custom quote", 1)[0].strip()

                if not message_to_send:
                    message_to_send = f"Hello Meysam Deris, I am interested in the services discussed in the chat."

                # Return the structured data to the front end
                return JsonResponse({
                    'ai_response': ai_response_text,
                    'whatsapp_redirect': True,
                    'whatsapp_number': WHATSAPP_NUMBER,
                    'whatsapp_message': message_to_send
                })

            return JsonResponse({'ai_response': ai_response_text})

        except Exception as e:
            error_message = str(e)

            if "503 UNAVAILABLE" in error_message and attempt < MAX_RETRIES - 1:
                print(f"Attempt {attempt + 1} failed (503 UNAVAILABLE). Retrying in 2 seconds...")
                time.sleep(2)
            else:
                print(f"Gemini API error after {attempt + 1} attempts: {e}")
                return JsonResponse({'ai_response': 'Sorry, the AI chatbot is currently overloaded or unavailable.'}, status=500)

    return JsonResponse({'ai_response': 'Maximum retries reached. Service remains unavailable.'}, status=503)